// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HmeDocumentDataSlicesSlice = FeaturedProductsSlice;

/**
 * Content for home documents
 */
interface HmeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: hme.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HmeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: hme.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: hme.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hme.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `hme`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HmeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HmeDocumentData>, "hme", Lang>;

export type AllDocumentTypes = HmeDocument;

/**
 * Item in *HomeHero → Default → Primary → ctaButtons*
 */
export interface FeaturedProductsSliceDefaultPrimaryCtabuttonsItem {
  /**
   * ctaButton field in *HomeHero → Default → Primary → ctaButtons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: /shop
   * - **API ID Path**: featured_products.default.primary.ctabuttons[].ctabutton
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ctabutton: prismic.LinkField;
}

/**
 * Primary content in *HomeHero → Default → Primary*
 */
export interface FeaturedProductsSliceDefaultPrimary {
  /**
   * heroTitle field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Discover the Beauty of Kyanite
   * - **API ID Path**: featured_products.default.primary.herotitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herotitle: prismic.KeyTextField;

  /**
   * heroDescription field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Exquisite jewelry crafted with the finest Nepalese kyanite and precious gemstones.
   * - **API ID Path**: featured_products.default.primary.herodescription
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  herodescription: prismic.KeyTextField;

  /**
   * imageUrl field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: https://t3.ftcdn.net/jpg/09/35/35/74/360_F_935357401_HqLmEodQnYeiUqxhOA33n9NXwahMb0EQ.jpg
   * - **API ID Path**: featured_products.default.primary.imageurl
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  imageurl: prismic.LinkToMediaField;

  /**
   * ctaButtons field in *HomeHero → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_products.default.primary.ctabuttons[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  ctabuttons: prismic.GroupField<
    Simplify<FeaturedProductsSliceDefaultPrimaryCtabuttonsItem>
  >;
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedProductsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HomeHero*
 */
type FeaturedProductsSliceVariation = FeaturedProductsSliceDefault;

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `featured_products`
 * - **Description**: FeaturedProducts
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProductsSlice = prismic.SharedSlice<
  "featured_products",
  FeaturedProductsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HmeDocument,
      HmeDocumentData,
      HmeDocumentDataSlicesSlice,
      AllDocumentTypes,
      FeaturedProductsSlice,
      FeaturedProductsSliceDefaultPrimaryCtabuttonsItem,
      FeaturedProductsSliceDefaultPrimary,
      FeaturedProductsSliceVariation,
      FeaturedProductsSliceDefault,
    };
  }
}
