import type { Metadata } from "next";
import { Comfortaa as Font } from "next/font/google";
import "./globals.css";
import { Layout } from "./_components/layout";

const font = Font({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className} style={{ colorScheme: "light", backgroundColor: "whitesmoke" }}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
