import type { Metadata } from "next";
import { Comfortaa as Font } from "next/font/google";
import "./globals.css";
import { Layout } from "./_components/layout";

const font = Font({})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
