// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  call_to_action: dynamic(() => import("./CallToAction")),
  featured_products: dynamic(() => import("./HomeHero")),
  hero: dynamic(() => import("./Hero")),
};
