// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_section: dynamic(() => import("./AboutUsSection")),
  featured_products: dynamic(() => import("./FeaturedProducts")),
  hero: dynamic(() => import("./Hero")),
};
